export const ADD_INGRDIENT = 'ADD_INGRDIENT';
export const REMOVE_INGREDEINT = 'REMOVE_INGREDEINT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';

export const BUGER_PURCHASE_SUCCESS = 'BUGER_PURCHASE_SUCCESS';
export const BURGER_PURCHASE_FAILED = 'BURGER_PURCHASE_FAILED';
export const BURGER_PURCHASE_START = 'BURGER_PURCHASE_START';
export const PURCHASE_INIT = 'PURCHASE_INIT';