export const ADD_INGRDIENT = 'ADD_INGRDIENT';
export const REMOVE_INGREDEINT = 'REMOVE_INGREDEINT';
export const SET_INGREDIENTS = 'SET_INGREDIENTS';
export const FETCH_INGREDIENTS_FAILED = 'FETCH_INGREDIENTS_FAILED';